spring:
  #Configurações do spring
  datasource:
    url: jdbc:h2:mem:sdw2023
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      # create para criar as tabelas
      ddl-auto: create # validate / update / create / create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console #Path para acessar o banco via navegador
      settings:
        trace: false
        web-allow-others: false