spring:
  datasource:
    url: postgresql://postgres:jyeneTrNNsGaISzoHZnuCcJENgQWLmHS@postgres.railway.internal:5432/railway
    #username: ${PGUSER}
    #password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
  logging:
    level:
      org.springframework: DEBUG
      org.hibernate: DEBUG